// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for Status.
const (
	Booting  Status = "Booting"
	Running  Status = "Running"
	Stopped  Status = "Stopped"
	Stopping Status = "Stopping"
	Unknown  Status = "Unknown"
)

// Base defines model for Base.
type Base struct {
	Cpu     uint64 `json:"cpu"`
	Id      string `json:"id"`
	Name    string `json:"name"`
	Ram     uint64 `json:"ram"`
	Storage uint64 `json:"storage"`
}

// Instance defines model for Instance.
type Instance struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Status Status `json:"status"`
}

// Status defines model for Status.
type Status string

// PostVestaV1BasesIdCloneJSONBody defines parameters for PostVestaV1BasesIdClone.
type PostVestaV1BasesIdCloneJSONBody struct {
	Name string `json:"name"`

	// Ram byte 단위, 설정하지 않으면 기존 base ram 크기 유지
	Ram *uint64 `json:"ram,omitempty"`

	// Storage byte 단위, 설정하지 않으면 기존 base storage 크기 유지
	Storage *uint64 `json:"storage,omitempty"`
}

// PostVestaV1BasesIdCloneJSONRequestBody defines body for PostVestaV1BasesIdClone for application/json ContentType.
type PostVestaV1BasesIdCloneJSONRequestBody PostVestaV1BasesIdCloneJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// list bases
	// (GET /vesta/v1/bases)
	ListBases(w http.ResponseWriter, r *http.Request)
	// delete base
	// (DELETE /vesta/v1/bases/{id})
	DeleteVestaV1BasesId(w http.ResponseWriter, r *http.Request, id string)
	// clone base
	// (POST /vesta/v1/bases/{id}/clone)
	PostVestaV1BasesIdClone(w http.ResponseWriter, r *http.Request, id string)
	// list instances
	// (GET /vesta/v1/instances)
	ListInstances(w http.ResponseWriter, r *http.Request)
	// delete instance
	// (DELETE /vesta/v1/instances/{id})
	DeleteVestaV1InstancesId(w http.ResponseWriter, r *http.Request, id string)
	// promote instance
	// (POST /vesta/v1/instances/{id}/promote)
	PostVestaV1InstancesIdPromote(w http.ResponseWriter, r *http.Request, id string)
	// start instance
	// (POST /vesta/v1/instances/{id}/start)
	PostVestaV1InstancesIdStart(w http.ResponseWriter, r *http.Request, id string)
	// stop instance
	// (POST /vesta/v1/instances/{id}/stop)
	PostVestaV1InstancesIdStop(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// list bases
// (GET /vesta/v1/bases)
func (_ Unimplemented) ListBases(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// delete base
// (DELETE /vesta/v1/bases/{id})
func (_ Unimplemented) DeleteVestaV1BasesId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// clone base
// (POST /vesta/v1/bases/{id}/clone)
func (_ Unimplemented) PostVestaV1BasesIdClone(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// list instances
// (GET /vesta/v1/instances)
func (_ Unimplemented) ListInstances(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// delete instance
// (DELETE /vesta/v1/instances/{id})
func (_ Unimplemented) DeleteVestaV1InstancesId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// promote instance
// (POST /vesta/v1/instances/{id}/promote)
func (_ Unimplemented) PostVestaV1InstancesIdPromote(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// start instance
// (POST /vesta/v1/instances/{id}/start)
func (_ Unimplemented) PostVestaV1InstancesIdStart(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// stop instance
// (POST /vesta/v1/instances/{id}/stop)
func (_ Unimplemented) PostVestaV1InstancesIdStop(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBases operation middleware
func (siw *ServerInterfaceWrapper) ListBases(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBases(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVestaV1BasesId operation middleware
func (siw *ServerInterfaceWrapper) DeleteVestaV1BasesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVestaV1BasesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVestaV1BasesIdClone operation middleware
func (siw *ServerInterfaceWrapper) PostVestaV1BasesIdClone(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVestaV1BasesIdClone(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInstances operation middleware
func (siw *ServerInterfaceWrapper) ListInstances(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInstances(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVestaV1InstancesId operation middleware
func (siw *ServerInterfaceWrapper) DeleteVestaV1InstancesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVestaV1InstancesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVestaV1InstancesIdPromote operation middleware
func (siw *ServerInterfaceWrapper) PostVestaV1InstancesIdPromote(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVestaV1InstancesIdPromote(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVestaV1InstancesIdStart operation middleware
func (siw *ServerInterfaceWrapper) PostVestaV1InstancesIdStart(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVestaV1InstancesIdStart(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVestaV1InstancesIdStop operation middleware
func (siw *ServerInterfaceWrapper) PostVestaV1InstancesIdStop(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVestaV1InstancesIdStop(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vesta/v1/bases", wrapper.ListBases)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/vesta/v1/bases/{id}", wrapper.DeleteVestaV1BasesId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vesta/v1/bases/{id}/clone", wrapper.PostVestaV1BasesIdClone)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vesta/v1/instances", wrapper.ListInstances)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/vesta/v1/instances/{id}", wrapper.DeleteVestaV1InstancesId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vesta/v1/instances/{id}/promote", wrapper.PostVestaV1InstancesIdPromote)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vesta/v1/instances/{id}/start", wrapper.PostVestaV1InstancesIdStart)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vesta/v1/instances/{id}/stop", wrapper.PostVestaV1InstancesIdStop)
	})

	return r
}

type ListBasesRequestObject struct {
}

type ListBasesResponseObject interface {
	VisitListBasesResponse(w http.ResponseWriter) error
}

type ListBases200JSONResponse []Base

func (response ListBases200JSONResponse) VisitListBasesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListBases204Response struct {
}

func (response ListBases204Response) VisitListBasesResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteVestaV1BasesIdRequestObject struct {
	Id string `json:"id"`
}

type DeleteVestaV1BasesIdResponseObject interface {
	VisitDeleteVestaV1BasesIdResponse(w http.ResponseWriter) error
}

type DeleteVestaV1BasesId204Response struct {
}

func (response DeleteVestaV1BasesId204Response) VisitDeleteVestaV1BasesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteVestaV1BasesId404JSONResponse struct {
	BaseId string `json:"base_id"`
}

func (response DeleteVestaV1BasesId404JSONResponse) VisitDeleteVestaV1BasesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostVestaV1BasesIdCloneRequestObject struct {
	Id   string `json:"id"`
	Body *PostVestaV1BasesIdCloneJSONRequestBody
}

type PostVestaV1BasesIdCloneResponseObject interface {
	VisitPostVestaV1BasesIdCloneResponse(w http.ResponseWriter) error
}

type PostVestaV1BasesIdClone200JSONResponse struct {
	Id      string `json:"id"`
	Name    string `json:"name"`
	Ram     uint64 `json:"ram"`
	Storage uint64 `json:"storage"`
}

func (response PostVestaV1BasesIdClone200JSONResponse) VisitPostVestaV1BasesIdCloneResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostVestaV1BasesIdClone404JSONResponse struct {
	BaseId string `json:"base_id"`
}

func (response PostVestaV1BasesIdClone404JSONResponse) VisitPostVestaV1BasesIdCloneResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostVestaV1BasesIdClone503JSONResponse struct {
	BaseId string `json:"base_id"`
}

func (response PostVestaV1BasesIdClone503JSONResponse) VisitPostVestaV1BasesIdCloneResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type ListInstancesRequestObject struct {
}

type ListInstancesResponseObject interface {
	VisitListInstancesResponse(w http.ResponseWriter) error
}

type ListInstances200JSONResponse []Instance

func (response ListInstances200JSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListInstances204Response struct {
}

func (response ListInstances204Response) VisitListInstancesResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteVestaV1InstancesIdRequestObject struct {
	Id string `json:"id"`
}

type DeleteVestaV1InstancesIdResponseObject interface {
	VisitDeleteVestaV1InstancesIdResponse(w http.ResponseWriter) error
}

type DeleteVestaV1InstancesId204Response struct {
}

func (response DeleteVestaV1InstancesId204Response) VisitDeleteVestaV1InstancesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteVestaV1InstancesId404JSONResponse struct {
	InstanceId string `json:"instance_id"`
}

func (response DeleteVestaV1InstancesId404JSONResponse) VisitDeleteVestaV1InstancesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostVestaV1InstancesIdPromoteRequestObject struct {
	Id string `json:"id"`
}

type PostVestaV1InstancesIdPromoteResponseObject interface {
	VisitPostVestaV1InstancesIdPromoteResponse(w http.ResponseWriter) error
}

type PostVestaV1InstancesIdPromote200JSONResponse Base

func (response PostVestaV1InstancesIdPromote200JSONResponse) VisitPostVestaV1InstancesIdPromoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostVestaV1InstancesIdPromote404JSONResponse struct {
	InstanceId string `json:"instance_id"`
}

func (response PostVestaV1InstancesIdPromote404JSONResponse) VisitPostVestaV1InstancesIdPromoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostVestaV1InstancesIdStartRequestObject struct {
	Id string `json:"id"`
}

type PostVestaV1InstancesIdStartResponseObject interface {
	VisitPostVestaV1InstancesIdStartResponse(w http.ResponseWriter) error
}

type PostVestaV1InstancesIdStart200JSONResponse Instance

func (response PostVestaV1InstancesIdStart200JSONResponse) VisitPostVestaV1InstancesIdStartResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostVestaV1InstancesIdStart404JSONResponse struct {
	InstanceId string `json:"instance_id"`
}

func (response PostVestaV1InstancesIdStart404JSONResponse) VisitPostVestaV1InstancesIdStartResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostVestaV1InstancesIdStart409JSONResponse struct {
	InstanceId string `json:"instance_id"`
}

func (response PostVestaV1InstancesIdStart409JSONResponse) VisitPostVestaV1InstancesIdStartResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostVestaV1InstancesIdStopRequestObject struct {
	Id string `json:"id"`
}

type PostVestaV1InstancesIdStopResponseObject interface {
	VisitPostVestaV1InstancesIdStopResponse(w http.ResponseWriter) error
}

type PostVestaV1InstancesIdStop200JSONResponse Instance

func (response PostVestaV1InstancesIdStop200JSONResponse) VisitPostVestaV1InstancesIdStopResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostVestaV1InstancesIdStop404JSONResponse struct {
	InstanceId string `json:"instance_id"`
}

func (response PostVestaV1InstancesIdStop404JSONResponse) VisitPostVestaV1InstancesIdStopResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostVestaV1InstancesIdStop409JSONResponse struct {
	InstanceId string `json:"instance_id"`
}

func (response PostVestaV1InstancesIdStop409JSONResponse) VisitPostVestaV1InstancesIdStopResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// list bases
	// (GET /vesta/v1/bases)
	ListBases(ctx context.Context, request ListBasesRequestObject) (ListBasesResponseObject, error)
	// delete base
	// (DELETE /vesta/v1/bases/{id})
	DeleteVestaV1BasesId(ctx context.Context, request DeleteVestaV1BasesIdRequestObject) (DeleteVestaV1BasesIdResponseObject, error)
	// clone base
	// (POST /vesta/v1/bases/{id}/clone)
	PostVestaV1BasesIdClone(ctx context.Context, request PostVestaV1BasesIdCloneRequestObject) (PostVestaV1BasesIdCloneResponseObject, error)
	// list instances
	// (GET /vesta/v1/instances)
	ListInstances(ctx context.Context, request ListInstancesRequestObject) (ListInstancesResponseObject, error)
	// delete instance
	// (DELETE /vesta/v1/instances/{id})
	DeleteVestaV1InstancesId(ctx context.Context, request DeleteVestaV1InstancesIdRequestObject) (DeleteVestaV1InstancesIdResponseObject, error)
	// promote instance
	// (POST /vesta/v1/instances/{id}/promote)
	PostVestaV1InstancesIdPromote(ctx context.Context, request PostVestaV1InstancesIdPromoteRequestObject) (PostVestaV1InstancesIdPromoteResponseObject, error)
	// start instance
	// (POST /vesta/v1/instances/{id}/start)
	PostVestaV1InstancesIdStart(ctx context.Context, request PostVestaV1InstancesIdStartRequestObject) (PostVestaV1InstancesIdStartResponseObject, error)
	// stop instance
	// (POST /vesta/v1/instances/{id}/stop)
	PostVestaV1InstancesIdStop(ctx context.Context, request PostVestaV1InstancesIdStopRequestObject) (PostVestaV1InstancesIdStopResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListBases operation middleware
func (sh *strictHandler) ListBases(w http.ResponseWriter, r *http.Request) {
	var request ListBasesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBases(ctx, request.(ListBasesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBases")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBasesResponseObject); ok {
		if err := validResponse.VisitListBasesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteVestaV1BasesId operation middleware
func (sh *strictHandler) DeleteVestaV1BasesId(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteVestaV1BasesIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteVestaV1BasesId(ctx, request.(DeleteVestaV1BasesIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteVestaV1BasesId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteVestaV1BasesIdResponseObject); ok {
		if err := validResponse.VisitDeleteVestaV1BasesIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostVestaV1BasesIdClone operation middleware
func (sh *strictHandler) PostVestaV1BasesIdClone(w http.ResponseWriter, r *http.Request, id string) {
	var request PostVestaV1BasesIdCloneRequestObject

	request.Id = id

	var body PostVestaV1BasesIdCloneJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostVestaV1BasesIdClone(ctx, request.(PostVestaV1BasesIdCloneRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostVestaV1BasesIdClone")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostVestaV1BasesIdCloneResponseObject); ok {
		if err := validResponse.VisitPostVestaV1BasesIdCloneResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListInstances operation middleware
func (sh *strictHandler) ListInstances(w http.ResponseWriter, r *http.Request) {
	var request ListInstancesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListInstances(ctx, request.(ListInstancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInstances")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListInstancesResponseObject); ok {
		if err := validResponse.VisitListInstancesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteVestaV1InstancesId operation middleware
func (sh *strictHandler) DeleteVestaV1InstancesId(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteVestaV1InstancesIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteVestaV1InstancesId(ctx, request.(DeleteVestaV1InstancesIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteVestaV1InstancesId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteVestaV1InstancesIdResponseObject); ok {
		if err := validResponse.VisitDeleteVestaV1InstancesIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostVestaV1InstancesIdPromote operation middleware
func (sh *strictHandler) PostVestaV1InstancesIdPromote(w http.ResponseWriter, r *http.Request, id string) {
	var request PostVestaV1InstancesIdPromoteRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostVestaV1InstancesIdPromote(ctx, request.(PostVestaV1InstancesIdPromoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostVestaV1InstancesIdPromote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostVestaV1InstancesIdPromoteResponseObject); ok {
		if err := validResponse.VisitPostVestaV1InstancesIdPromoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostVestaV1InstancesIdStart operation middleware
func (sh *strictHandler) PostVestaV1InstancesIdStart(w http.ResponseWriter, r *http.Request, id string) {
	var request PostVestaV1InstancesIdStartRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostVestaV1InstancesIdStart(ctx, request.(PostVestaV1InstancesIdStartRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostVestaV1InstancesIdStart")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostVestaV1InstancesIdStartResponseObject); ok {
		if err := validResponse.VisitPostVestaV1InstancesIdStartResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostVestaV1InstancesIdStop operation middleware
func (sh *strictHandler) PostVestaV1InstancesIdStop(w http.ResponseWriter, r *http.Request, id string) {
	var request PostVestaV1InstancesIdStopRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostVestaV1InstancesIdStop(ctx, request.(PostVestaV1InstancesIdStopRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostVestaV1InstancesIdStop")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostVestaV1InstancesIdStopResponseObject); ok {
		if err := validResponse.VisitPostVestaV1InstancesIdStopResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
